default: anisotropiefilter

anisotropiefilter: PreProcessing.cpp PreProcessing.h Anisotropiefilter.cpp Anisotropiefilter.h Benchmarking.cpp Benchmarking.h
	g++ -I /home/adim/OpenCV-2.2.0/include/opencv -L /home/adim/OpenCV-2.2.0/lib PreProcessing.cpp Anisotropiefilter.cpp Benchmarking.cpp -l opencv_highgui -l opencv_core -lrt -o anisotropiefilter.out

