compile:
	g++ test.cpp -lpthread -o test

compile-orig:
	g++ test-orig.cpp -lpthread -o test-orig

compile-badrm:
	g++ test-badrm.cpp -lpthread -o test-badrm

compile-badloop:
	g++ test-badloop.cpp -lpthread -o test-badloop

compile-buffers:
	$(CC) $(CFLAGS) test-buffers.c -lpthread -o test-buffers

compile-simple:
	$(CC) $(CFLAGS) test-simple.c -lpthread -o test-simple
